import test from "node:test";
import assert from "node:assert/strict";
import { loadConfig } from "../config";

test("loadConfig returns expected default service topology", () => {
  delete process.env.OLLAMA_ENDPOINT;
  delete process.env.WHISPER_ENDPOINT;
  delete process.env.PIPER_ENDPOINT;
  delete process.env.ENABLE_WHISPER_HTTP;
  delete process.env.ENABLE_PIPER_HTTP;
  delete process.env.AUDIO_RECORD_SECONDS;
  delete process.env.AUDIO_SAMPLE_RATE;
  delete process.env.ENABLE_AUDIO_PLAYBACK_DEBUG;
  delete process.env.WHISPER_LANGUAGE;
  delete process.env.ENABLE_TTS;
  delete process.env.ENABLE_RAG;
  delete process.env.RAG_SOURCE_DIR;
  delete process.env.RAG_STORE_PATH;
  delete process.env.RAG_CHUNK_SIZE;
  delete process.env.RAG_CHUNK_OVERLAP;
  delete process.env.RAG_TOP_K;
  delete process.env.RAG_EXTRACTOR_PYTHON;
  delete process.env.OLLAMA_SYSTEM_PROMPT;
  delete process.env.PIPER_BINARY_PATH;
  delete process.env.PIPER_MODEL_PATH;

  const config = loadConfig();
  assert.equal(config.services.length, 3);
  assert.equal(config.services[0]?.name, "ollama");
  assert.equal(config.services[0]?.enabled, true);
  assert.equal(config.services[1]?.name, "whisper");
  assert.equal(config.services[1]?.enabled, true);
  assert.equal(config.services[2]?.name, "piper");
  assert.equal(config.services[2]?.enabled, false);
  assert.equal(config.audioRecordSeconds, 5);
  assert.equal(config.audioSampleRate, 16000);
  assert.equal(config.enableAudioPlaybackDebug, false);
  assert.equal(config.whisperLanguage, "en");
  assert.equal(config.enableTts, true);
  assert.equal(config.enableRag, true);
  assert.equal(config.ragSourceDir, "/opt/svkrishna/rag/inbox");
  assert.equal(config.ragStorePath, "/opt/svkrishna/rag/store.json");
  assert.equal(config.ragChunkSize, 120);
  assert.equal(config.ragChunkOverlap, 30);
  assert.equal(config.ragTopK, 4);
  assert.equal(config.ragExtractorPython, "python3");
  assert.match(config.ollamaSystemPrompt, /offline boat assistant/i);
  assert.equal(config.piperBinaryPath, "piper");
  assert.equal(config.piperModelPath, "/path/to/piper/voice/model.onnx");
});
